SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+02:00";

CREATE DATABASE MEDS;

USE MEDS;

CREATE TABLE MEDS_DATA_CONTENT (
  DATA_CONTENT_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  DATA            BLOB       NOT NULL,

  PRIMARY KEY (DATA_CONTENT_ID),
  UNIQUE KEY DATA_CONTENT_ID(DATA_CONTENT_ID)
);

CREATE TABLE MEDS_FILE (
  FILE_ID         BIGINT(15)    NOT NULL AUTO_INCREMENT,
  GUID            VARCHAR(50)   NOT NULL,
  NAME            VARCHAR(50)   NOT NULL,
  EFF_FRM         DATETIME      NOT NULL,

  PRIMARY KEY (FILE_ID),
  UNIQUE KEY FILE_ID(FILE_ID),
  UNIQUE KEY GUID(GUID)
);

CREATE TABLE MEDS_IMAGE (
  IMAGE_ID        BIGINT(15)  NOT NULL AUTO_INCREMENT,
  FILE_ID         BIGINT(50)  NOT NULL,
  WIDTH           INT(5)      NOT NULL,
  HEIGHT          INT(5)      NOT NULL,

  PRIMARY KEY (IMAGE_ID),
  UNIQUE KEY IMAGE_ID(IMAGE_ID),
  FOREIGN KEY (FILE_ID) REFERENCES MEDS_FILE (FILE_ID)
);

CREATE TABLE MEDS_USER (
  USER_ID         BIGINT(15)    NOT NULL AUTO_INCREMENT,
  EMAIL           VARCHAR(50)   NOT NULL,
  PASSWORD        VARCHAR(255)  NOT NULL,
  NAME            VARCHAR(20)   NULL,
  SURNAME         VARCHAR(20)   NULL,
  PHONE           VARCHAR(15)   NULL,
  GENDER          VARCHAR(9)    NULL,
  AGE             INT(4)        NULL,
  USER_ALLOW_PUSH BOOLEAN       NOT NULL,

  PRIMARY KEY (USER_ID),
  UNIQUE KEY USER_ID(USER_ID),
  UNIQUE KEY EMAIL(EMAIL)
);

CREATE TABLE MEDS_PERMISSION (
  PERMISSION_ID         BIGINT(15)  NOT NULL AUTO_INCREMENT,
  PERMISSION_NAME       VARCHAR(50) NOT NULL,

  PRIMARY KEY (PERMISSION_ID),
  UNIQUE KEY PERMISSION_ID(PERMISSION_ID),
  UNIQUE KEY PERMISSION_NAME(PERMISSION_NAME)
);

CREATE TABLE MEDS_USER_PERMISSION (
  USER_PERMISSION_ID  BIGINT(15)  NOT NULL AUTO_INCREMENT,
  USER_ID             BIGINT(15)  NOT NULL,
  PERMISSION_ID       BIGINT(15)  NOT NULL,

  PRIMARY KEY (USER_PERMISSION_ID),
  UNIQUE KEY USER_PERMISSION_ID(USER_PERMISSION_ID),
  FOREIGN KEY (USER_ID) REFERENCES MEDS_USER (USER_ID),
  FOREIGN KEY (PERMISSION_ID) REFERENCES MEDS_PERMISSION (PERMISSION_ID)
);

CREATE TABLE MEDS_DEVICES_TYPE (
  DEVICES_TYPE_ID BIGINT(15)  NOT NULL  AUTO_INCREMENT,
  TYPE_NAME       VARCHAR(50) NOT NULL,
  CAN_PUSH        BOOLEAN     NOT NULL,

  PRIMARY KEY (DEVICES_TYPE_ID),
  UNIQUE KEY DEVICES_TYPE_ID(DEVICES_TYPE_ID)
);

CREATE TABLE MEDS_USER_DEVICE (
  USER_DEVICES_ID BIGINT(15)  NOT NULL AUTO_INCREMENT,
  USER_ID         BIGINT(15)  NOT NULL,
  TYPE_ID         BIGINT(15)  NOT NULL,
  NAME            VARCHAR(50) NOT NULL,
  DEVICE_PUSH_ID  VARCHAR(50) NOT NULL,

  PRIMARY KEY (USER_DEVICES_ID),
  UNIQUE KEY USER_DEVICES_ID(USER_DEVICES_ID),
  FOREIGN KEY (USER_ID) REFERENCES MEDS_USER (USER_ID),
  FOREIGN KEY (TYPE_ID) REFERENCES MEDS_DEVICES_TYPE (DEVICES_TYPE_ID)
);

CREATE TABLE MEDS_TRADING_HOUR (
  TRADING_HOUR_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  EFF_FRM         TIME       NULL,
  EFF_TO          TIME       NULL,
  OPEN            BOOLEAN    NOT NULL,

  PRIMARY KEY (TRADING_HOUR_ID),
  UNIQUE KEY TRADING_HOUR_ID(TRADING_HOUR_ID)
);

CREATE TABLE MEDS_TRADING_DAY (
  TRADING_DAY_ID          BIGINT(15) NOT NULL AUTO_INCREMENT,
  MONDAY_ID               BIGINT(15) NOT NULL,
  TUESDAY_ID              BIGINT(15) NOT NULL,
  WEDNESDAY_ID            BIGINT(15) NOT NULL,
  THURSDAY_ID             BIGINT(15) NOT NULL,
  FRIDAY_ID               BIGINT(15) NOT NULL,
  SATURDAY_ID             BIGINT(15) NOT NULL,
  SUNDAY_ID               BIGINT(15) NOT NULL,
  PUBIC_HOLIDAY_ID        BIGINT(15) NOT NULL,

  PRIMARY KEY (TRADING_DAY_ID),
  UNIQUE KEY TRADING_DAY_ID(TRADING_DAY_ID),
  FOREIGN KEY (MONDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (TUESDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (WEDNESDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (THURSDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (FRIDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (SATURDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (SUNDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (PUBIC_HOLIDAY_ID) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID)
);

CREATE TABLE MEDS_FIELD (
  FIELD_ID      BIGINT(15) NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(20) NOT NULL,
  MAP_COLOR     VARCHAR(6) NOT NULL,

  PRIMARY KEY (FIELD_ID),
  UNIQUE KEY FIELD_ID(FIELD_ID)
);

CREATE TABLE MEDS_PRACTICE (
  PRACTICE_ID         BIGINT(15)    NOT NULL AUTO_INCREMENT,
  NAME                VARCHAR(50)   NULL,
  EMAIL               VARCHAR(50)   NOT NULL,
  LONGITUDE           FLOAT(30)     NOT NULL,
  LATITUDE            FLOAT(30)     NOT NULL,
  ADDRESS             VARCHAR(200)  NOT NULL,
  TRADING_DAY_ID      BIGINT(15)    NOT NULL,
  PHONE               VARCHAR(20)   NULL,
  FEE                 FLOAT(30)     NULL,
  IMAGE_ID            BIGINT(15)    NOT NULL,
  BIO_ID              BIGINT(15)    NOT NULL,

  PRIMARY KEY (PRACTICE_ID),
  UNIQUE KEY PRACTICE_ID(PRACTICE_ID),
  FOREIGN KEY (TRADING_DAY_ID) REFERENCES MEDS_TRADING_DAY (TRADING_DAY_ID),
  FOREIGN KEY (IMAGE_ID) REFERENCES MEDS_IMAGE (IMAGE_ID),
  FOREIGN KEY (BIO_ID) REFERENCES MEDS_DATA_CONTENT (DATA_CONTENT_ID)
);

CREATE TABLE MEDS_PRACTICE_FIELD (
  PRACTICE_FIELD_ID     BIGINT(15) NOT NULL AUTO_INCREMENT,
  FIELD_ID              BIGINT(15) NOT NULL,
  PRACTICE_ID           BIGINT(15) NOT NULL,

  PRIMARY KEY (PRACTICE_FIELD_ID),
  UNIQUE KEY PRACTICE_FIELD_ID(PRACTICE_FIELD_ID),
  FOREIGN KEY (FIELD_ID) REFERENCES MEDS_FIELD (FIELD_ID),
  FOREIGN KEY (PRACTICE_ID) REFERENCES MEDS_PRACTICE (PRACTICE_ID)
);

CREATE TABLE MEDS_DOCTOR (
  DOCTOR_ID     BIGINT(15) NOT NULL AUTO_INCREMENT,
  USER_ID       BIGINT(15) NOT NULL,
  ICON_ID       BIGINT(15) NOT NULL,
  IMAGE_ID      BIGINT(15) NOT NULL,
  BIO_ID        BIGINT(15) NOT NULL,

  PRIMARY KEY (DOCTOR_ID),
  UNIQUE KEY DOCTOR_ID(DOCTOR_ID),
  FOREIGN KEY (IMAGE_ID) REFERENCES MEDS_IMAGE (IMAGE_ID),
  FOREIGN KEY (ICON_ID) REFERENCES MEDS_IMAGE (IMAGE_ID),
  FOREIGN KEY (USER_ID) REFERENCES MEDS_USER (USER_ID),
  FOREIGN KEY (BIO_ID) REFERENCES MEDS_DATA_CONTENT (DATA_CONTENT_ID)
);

CREATE TABLE MEDS_DOCTOR_FIELD (
  DOCTOR_FIELD_ID     BIGINT(15) NOT NULL AUTO_INCREMENT,
  FIELD_ID            BIGINT(15) NOT NULL,
  DOCTOR_ID           BIGINT(15) NOT NULL,

  PRIMARY KEY (DOCTOR_FIELD_ID),
  UNIQUE KEY DOCTOR_FIELD_ID(DOCTOR_FIELD_ID),
  FOREIGN KEY (FIELD_ID) REFERENCES MEDS_FIELD (FIELD_ID),
  FOREIGN KEY (DOCTOR_ID) REFERENCES MEDS_DOCTOR (DOCTOR_ID)
);

CREATE TABLE MEDS_DOCTOR_PRACTICE (
  MEDS_DOCTOR_PRACTICE_ID     BIGINT(15) NOT NULL AUTO_INCREMENT,
  PRACTICE_ID                 BIGINT(15) NOT NULL,
  DOCTOR_ID                   BIGINT(15) NOT NULL,

  PRIMARY KEY (MEDS_DOCTOR_PRACTICE_ID),
  UNIQUE KEY MEDS_DOCTOR_PRACTICE_ID(MEDS_DOCTOR_PRACTICE_ID),
  FOREIGN KEY (PRACTICE_ID) REFERENCES MEDS_PRACTICE (PRACTICE_ID),
  FOREIGN KEY (DOCTOR_ID) REFERENCES MEDS_DOCTOR (DOCTOR_ID)
);

CREATE TABLE MEDS_APPOINTMENT (
  APPOINTMENT_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  PRACTICE_ID    BIGINT(15) NOT NULL,
  USER_ID        BIGINT(15) NOT NULL,
  NOTE_ID        BIGINT(15) NULL,
  EXPECTED_FRM   DATETIME   NOT NULL,
  EXPECTED_TO    DATETIME   NOT NULL,
  ACTUAL_FRM     DATETIME   NULL,
  ACTUAL_TO      DATETIME   NULL,

  PRIMARY KEY (APPOINTMENT_ID),
  UNIQUE KEY APPOINTMENT_ID(APPOINTMENT_ID),
  FOREIGN KEY (PRACTICE_ID) REFERENCES MEDS_PRACTICE (PRACTICE_ID),
  FOREIGN KEY (USER_ID) REFERENCES MEDS_USER (USER_ID),
  FOREIGN KEY (NOTE_ID) REFERENCES MEDS_DATA_CONTENT (DATA_CONTENT_ID)
);

CREATE TABLE MEDS_DOCTOR_APPOINTMENT (
  MEDS_DOCTOR_APPOINTMENT_ID      BIGINT(15) NOT NULL AUTO_INCREMENT,
  APPOINTMENT_ID                  BIGINT(15) NOT NULL,
  DOCTOR_ID                       BIGINT(15) NOT NULL,

  PRIMARY KEY (MEDS_DOCTOR_APPOINTMENT_ID),
  UNIQUE KEY MEDS_DOCTOR_APPOINTMENT_ID(MEDS_DOCTOR_APPOINTMENT_ID),
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES MEDS_APPOINTMENT (APPOINTMENT_ID),
  FOREIGN KEY (DOCTOR_ID) REFERENCES MEDS_DOCTOR (DOCTOR_ID)
);

CREATE TABLE MEDS_PRESCRIPTION (
  PRESCRIPTION_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  APPOINTMENT_ID  BIGINT(15) NOT NULL,
  DOCTOR_ID       BIGINT(15) NOT NULL,
  USER_ID         BIGINT(15) NOT NULL,
  FILE_ID         BIGINT(15) NOT NULL,
  EFF_FRM         DATETIME   NOT NULL,
  EFF_TO          DATETIME   NOT NULL,

  PRIMARY KEY (PRESCRIPTION_ID),
  UNIQUE KEY PRESCRIPTION_ID(PRESCRIPTION_ID),
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES MEDS_APPOINTMENT (APPOINTMENT_ID),
  FOREIGN KEY (DOCTOR_ID) REFERENCES MEDS_DOCTOR (DOCTOR_ID),
  FOREIGN KEY (USER_ID) REFERENCES MEDS_USER (USER_ID),
  FOREIGN KEY (FILE_ID) REFERENCES MEDS_FILE (FILE_ID)
);

CREATE TABLE MEDS_PRESCRIPTION_ITEM (
  PRESCRIPTION_ITEM_ID BIGINT(15)  NOT NULL AUTO_INCREMENT,
  PRESCRIPTION_ID      BIGINT(15)  NOT NULL,
  NAME                 VARCHAR(50) NOT NULL,

  PRIMARY KEY (PRESCRIPTION_ITEM_ID),
  UNIQUE KEY PRESCRIPTION_ITEM_ID(PRESCRIPTION_ITEM_ID),
  FOREIGN KEY (PRESCRIPTION_ID) REFERENCES MEDS_PRESCRIPTION (PRESCRIPTION_ID)
);