SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+02:00";

CREATE DATABASE MEDS;

USE MEDS;

CREATE TABLE MEDS_DATA_CONTENT (
  DATA_CONTENT_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  DATA            BLOB       NOT NULL,

  PRIMARY KEY (DATA_CONTENT_ID),
  UNIQUE KEY DATA_CONTENT_ID(DATA_CONTENT_ID)
);

CREATE TABLE MEDS_USER (
  USER_ID         BIGINT(15)  NOT NULL AUTO_INCREMENT,
  EMAIL           VARCHAR(50) NOT NULL,
  PASSWORD        VARCHAR(20) NOT NULL,
  NAME            VARCHAR(20) NULL,
  SURNAME         VARCHAR(20) NULL,
  PHONE           VARCHAR(15) NULL,
  GENDER          VARCHAR(9)  NULL,
  AGE             INT(4)      NULL,
  USER_ALLOW_PUSH BOOLEAN     NOT NULL,

  PRIMARY KEY (USER_ID),
  UNIQUE KEY USER_ID(USER_ID),
  UNIQUE KEY EMAIL(EMAIL)
);

CREATE TABLE MEDS_DEVICES_TYPE (
  DEVICES_TYPE_ID BIGINT(15)  NOT NULL  AUTO_INCREMENT,
  TYPE_NAME       VARCHAR(50) NOT NULL,
  CAN_PUSH        BOOLEAN     NOT NULL,

  PRIMARY KEY (DEVICES_TYPE_ID),
  UNIQUE KEY DEVICES_TYPE_ID(DEVICES_TYPE_ID)
);

CREATE TABLE MEDS_USER_DEVICE (
  USER_DEVICES_ID BIGINT(15)  NOT NULL AUTO_INCREMENT,
  USER            BIGINT(15)  NOT NULL,
  TYPE            BIGINT(15)  NOT NULL,
  NAME            VARCHAR(50) NOT NULL,
  DEVICE_PUSH_ID  VARCHAR(50) NOT NULL,

  PRIMARY KEY (USER_DEVICES_ID),
  UNIQUE KEY USER_DEVICES_ID(USER_DEVICES_ID),
  FOREIGN KEY (USER) REFERENCES MEDS_USER (USER_ID),
  FOREIGN KEY (TYPE) REFERENCES MEDS_DEVICES_TYPE (DEVICES_TYPE_ID)
);

CREATE TABLE MEDS_PRACTICE (
  PRACTICE_ID   BIGINT(15)   NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(50)  NULL,
  EMAIL         VARCHAR(50)  NOT NULL,
  LONGITUDE     FLOAT(30)    NOT NULL,
  LATITUDE      FLOAT(30)    NOT NULL,
  ADDRESS       VARCHAR(200) NOT NULL,
  TRADING_HOURS BIGINT(15)   NOT NULL,
  PHONE         VARCHAR(20)  NULL,
  FEE           FLOAT(30)    NULL,

  PRIMARY KEY (PRACTICE_ID),
  UNIQUE KEY PRACTICE_ID(PRACTICE_ID),
  FOREIGN KEY (TRADING_HOURS) REFERENCES MEDS_TRADING_HOUR_DAY (TRADING_HOUR_DAY_ID)
);

CREATE TABLE MEDS_TRADING_HOUR_DAY (
  TRADING_HOUR_DAY_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  MONDAY              BIGINT(15) NOT NULL,
  TUESDAY             BIGINT(15) NOT NULL,
  WEDNESSDAY          BIGINT(15) NOT NULL,
  THURSDAY            BIGINT(15) NOT NULL,
  FRIDAY              BIGINT(15) NOT NULL,
  SATURDAY            BIGINT(15) NOT NULL,
  SUNDAY              BIGINT(15) NOT NULL,
  PUBIC_HOLIDAY       BIGINT(15) NOT NULL,

  PRIMARY KEY (TRADING_HOUR_DAY_ID),
  UNIQUE KEY TRADING_HOUR_DAY_ID(TRADING_HOUR_DAY_ID),
  FOREIGN KEY (MONDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (TUESDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (WEDNESSDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (THURSDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (FRIDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (SATURDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (SUNDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID),
  FOREIGN KEY (PUBIC_HOLIDAY) REFERENCES MEDS_TRADING_HOUR (TRADING_HOUR_ID)
);

CREATE TABLE MEDS_TRADING_HOUR (
  TRADING_HOUR_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  EFF_FRM         TIME       NULL,
  EFF_TO          TIME       NULL,
  OPEN            BOOLEAN    NOT NULL,

  PRIMARY KEY (TRADING_HOUR_ID),
  UNIQUE KEY TRADING_HOUR_ID(TRADING_HOUR_ID)
);

CREATE TABLE MEDS_DOCTOR (
  DOCTOR_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  PRACTICE  BIGINT(15) NOT NULL,
  USER      BIGINT(15) NOT NULL,

  PRIMARY KEY (DOCTOR_ID),
  UNIQUE KEY DOCTOR_ID(DOCTOR_ID),
  FOREIGN KEY (PRACTICE) REFERENCES MEDS_PRACTICE (PRACTICE_ID),
  FOREIGN KEY (USER) REFERENCES MEDS_USER (USER_ID)
);

CREATE TABLE MEDS_APPOINTMENT (
  APPOINTMENT_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  PRACTICE       BIGINT(15) NOT NULL,
  USER           BIGINT(15) NOT NULL,
  EXPECTED_FRM   DATETIME   NOT NULL,
  EXPECTED_TO    DATETIME   NOT NULL,
  ACTUAL_FRM     DATETIME   NULL,
  ACTUAL_TO      DATETIME   NULL,

  PRIMARY KEY (APPOINTMENT_ID),
  UNIQUE KEY APPOINTMENT_ID(APPOINTMENT_ID),
  FOREIGN KEY (PRACTICE) REFERENCES MEDS_PRACTICE (PRACTICE_ID),
  FOREIGN KEY (USER) REFERENCES MEDS_USER (USER_ID)
);

CREATE TABLE MEDS_PRESCRIPTION (
  PRESCRIPTION_ID BIGINT(15) NOT NULL AUTO_INCREMENT,
  APPOINTMENT     BIGINT(15) NOT NULL,
  DOCTOR          BIGINT(15) NOT NULL,
  USER            BIGINT(15) NOT NULL,
  EFF_FRM         DATETIME   NOT NULL,
  EFF_TO          DATETIME   NOT NULL,

  PRIMARY KEY (PRESCRIPTION_ID),
  UNIQUE KEY PRESCRIPTION_ID(PRESCRIPTION_ID),
  FOREIGN KEY (APPOINTMENT) REFERENCES MEDS_APPOINTMENT (APPOINTMENT_ID),
  FOREIGN KEY (DOCTOR) REFERENCES MEDS_DOCTOR (DOCTOR_ID),
  FOREIGN KEY (USER) REFERENCES MEDS_USER (USER_ID)
);

CREATE TABLE MEDS_PRESCRIPTION_ITEM (
  PRESCRIPTION_ITEM_ID BIGINT(15)  NOT NULL AUTO_INCREMENT,
  PRESCRIPTION         BIGINT(15)  NOT NULL,
  NAME                 VARCHAR(50) NOT NULL,

  PRIMARY KEY (PRESCRIPTION_ITEM_ID),
  UNIQUE KEY PRESCRIPTION_ITEM_ID(PRESCRIPTION_ITEM_ID),
  FOREIGN KEY (PRESCRIPTION) REFERENCES MEDS_PRESCRIPTION (PRESCRIPTION_ID)
);